apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-db
  dataFrom:
    - extract:
        key: grafana-db
