apiVersion: v1
kind: Secret
metadata:
  name: grafana-db
  namespace: monitoring
stringData:
  type: postgres
  host: notes-postgresql.notes:5432
  name: grafana
  user: postgres
  password: postgres
