apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-keycloak-realm
data:
  notes-realm.json: |
    {
      "realm": "notes",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": true,
      "verifyEmail": false,
      "loginWithEmailAllowed": false,
      "requiredCredentials": ["password"],
      "clients": [
        {
          "clientId": "notes-app",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "email": "testuser@example.com",
          "emailVerified": true,
          "firstName": "Test",
          "lastName": "User",
          "requiredActions": [],
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": false
            }
          ]
        }
      ]
    }
