apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notes-keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: notes-keycloak
  dataFrom:
    - extract:
        key: keycloak
