apiVersion: v1
kind: Secret
metadata:
  name: notes-keycloak
stringData:
  KC_DB_URL: jdbc:postgresql://notes-postgresql:5432/keycloak
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: postgres
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
