{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "notes-backend.fullname" . }}
  labels:
    {{- include "notes-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.vault.secretStore }}
  target:
    name: {{ include "notes-backend.fullname" . }}
  dataFrom:
    - extract:
        key: {{ .Values.vault.secretKey }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-backend.fullname" . }}
  labels:
    {{- include "notes-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
{{- end }}
