apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-backend.fullname" . }}
  labels:
    {{- include "notes-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
