apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notes-backend.fullname" . }}
  labels:
    {{- include "notes-backend.labels" . | nindent 4 }}
data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.config.keycloakIssuerUri | quote }}
