apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-frontend.fullname" . }}
  labels:
    {{- include "notes-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "notes-frontend.selectorLabels" . | nindent 4 }}
